version: '3'

services:
        database:
                image: mariadb
                volumes:
                        - db_data:/var/lib/mysql
                restart: always
                environment:
                        MYSQL_ROOT_PASSWORD: rootpass
                        MYSQL_DATABASE: wordpress
                        MYSQL_USER: abhishek
                        MYSQL_PASSWORD: redhat

        wordpress:
                depends_on:
                        - database
                image: wordpress
                volumes:
                        - wordpress_files:/var/www/html
                ports:
                        - 8081:80
                restart: always
                environment:
                        WORDPRESS_DB_HOST: database
                        WORDPRESS_DB_USER: abhishek
                        WORDPRESS_DB_PASSWORD: redhat
                        WORDPRESS_DB_NAME: wordpress

volumes:
        wordpress_files:
        db_data:
