version: '3.1'

services:
        database:
                image: mariadb
                volumes:
                        - db_data:/var/lib/mysql
                restart: always
                environment:
                        MYSQL_ROOT_PASSWORD: rootpass
                        MYSQL_DATABASE: joom
                        MYSQL_USER: abhishek
                        MYSQL_PASSWORD: redhat

        wordpress:
                depends_on:
                        - database
                image:  joomla
                volumes:
                        - joomla_files:/var/www/html
                ports:
                        - 8081:80
                restart: always
                environment:
                        JOOMLA_DB_HOST: database
                        JOOMLA_DB_USER: abhishek
                        JOOMLA_DB_PASSWORD: redhat
                        JOOMLA_DB_NAME: joom

volumes:
        joomla_files:
        db_data:

